version: "3.7"
services:

  handler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: handler
    ports: 
      - "80:80"
    environment:
      - MODULE_NAME=image_handler
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    depends_on:
      - etcd

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
