apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-handler
#  namespace: rso
  labels:
    app: image-handler

spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-handler
  template:
    metadata:
      labels:
        app: image-handler
    spec:
      containers:
      - image: jakakokosar/image-handler:1.1.1
        name: image-handler
        env:
          - name: MODULE_NAME
            value: image_handler
          - name: PORT
            value: "8000"
        ports:
          - containerPort: 8000
            name: server
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: image-handler-service
#  namespace: rso
  labels:
    app: image-handler
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: server
  selector:
    app: image-handler